### ISSUE TITLE
Platform type should allow for extension

### ISSUE THREAD

**Issue by mpeg** [marko-js/run#15]
As discussed on Discord, wanted to document it here too

Currently you can extend the Context type as such:

```ts
declare module "@marko/run" {
  interface ContextExtensions {
    platform: WHATEVER
  }
}
```

When considering adding support for Cloudflare, it would be very helpful to be able to extend the Platform type in a similar way (ie maybe through a `PlatformExtensions` interface). Other adapters might also benefit, but particularly for Cloudflare this would allow for the end-user to specify their service binding types within their app code (as this would not be known ahead of time to the adapter code)

**Comment by rturnq** [comment]
Yeah, that makes sense. Currently the adapter can [specify a type](https://github.com/marko-js/run/blob/f2fbe82f0ef974b351d586e646e4567dadad2352/packages/adapters/netlify/src/index.ts#L127-L138) which gets written to the `.marko-run/routes.d.ts` but this doesn't let users easily extend it. I will add an extension interface to simply this.

**Comment by mpeg** [comment]
Thanks! I think that will be really helpful as in CF you usually would want to extend the Platform type to add your databases or other service bindings
