### ISSUE TITLE
Test file name shouldn't be used when generating types

### ISSUE THREAD

**Issue by sangxxh** [marko-js/run#39]
@marko/run@0.1.15
@marko@5.26.1

Create a `+middleware.test.ts` file next to `+middleware.ts`.
After that, the generated `.marko-run/routes.d.ts` is changed like this:

```diff
- declare module "../src/routes/+middleware" {
+ declare module "../src/routes/+middleware.test" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/path"];
    export type Context = Run.MultiRouteContext<Route>;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Route>;
  }
}
```

The module name shouldn't change to `.../+middleware.test`

**Comment by rturnq** [comment]
Hmm. This really should be an error as you are defining two conflicting middleware files. As it is we allow anything after a `.` following the +middleware, +layout, +page, etc. so you can provide additional details in you file name.

I don't really like the idea of special-casing certain suffixes like "test" or "spec". My recommendation would be name your test file `middleware.test.ts` without the plus so it doesn't get considered by the route builder.
